# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

def grupoSelecionado
	Grupo.order(quantidade: :asc).first
end

u=User.new
u.email = 'edmilton.ro@hotmail.com'
u.password = 'mari1009'
u.admin = true
u.save

Grupo.create(nome: "Grupo 1")
Grupo.create(nome: "Grupo 2")
Grupo.create(nome: "Grupo 3")
Grupo.create(nome: "Grupo 3")
Grupo.create(nome: "Grupo 5")
Grupo.create(nome: "Grupo 6")

grupoSelecionado.inscritos.create( nome: "Ademar Silva Rosa",  estado: "SP",  instituicao: "AMATRA II" )
grupoSelecionado.inscritos.create( nome: "Mylene Pereira Ramos",  estado: "SP",  instituicao: "AMATRA II" )
grupoSelecionado.inscritos.create( nome: "Marcos Dias de Castro",  estado: "SP",  instituicao: "AMATRA II"  )
grupoSelecionado.inscritos.create( nome: "Adriana Alves dos Santos Cruz",  estado: "SE", instituicao: "AJUFE" )
grupoSelecionado.inscritos.create( nome: "Clara da Mota Santos Pimenta Alves",  estado: ""  )
grupoSelecionado.inscritos.create( nome: "Dimis da Costa Braga",  estado: ""  )
grupoSelecionado.inscritos.create( nome: "Mara Lina Silva do Carmo",  estado: ""  )
grupoSelecionado.inscritos.create( nome: "Alcioni Escobar da Costa Alvim",  estado: ""  )
grupoSelecionado.inscritos.create( nome: "Eduardo Pereira da Silva",  estado: ""  )
grupoSelecionado.inscritos.create( nome: "LIDIVALDO REAICHE RAIMUNDO BRITTO",  estado: "BA",  instituicao: "AMAB" )
grupoSelecionado.inscritos.create( nome: "Andremara dos Santos",  estado: "BA",  instituicao: "AMAB"  )
grupoSelecionado.inscritos.create( nome: "Ângela Coelho de Salles Correia",  estado: "PB",  instituicao: "AMPB" )
grupoSelecionado.inscritos.create( nome: "Marcos Coelho de Salles",  estado: "PB",  instituicao: "AMPB"  )
grupoSelecionado.inscritos.create( nome: "KEYLLA RANYERE LOPES TEIXEIRA PROCÓPIO",  estado: "PI",  instituicao: "AMAPI" )
grupoSelecionado.inscritos.create( nome: "CARMEN MARIA PAIVA FERRAZ SOARES",  estado: "PI",  instituicao: "AMAPI"  )
grupoSelecionado.inscritos.create( nome: "Guilherme Diamantino de Oliveira Weber",  estado: "SE",  instituicao: "AMASE" )
grupoSelecionado.inscritos.create( nome: "ANTONIO HENRIQUE DE ALMEIDA SANTOS",  estado: "SE",  instituicao: "AMASE"  )
grupoSelecionado.inscritos.create( nome: "carolina valadares bitencourt",  estado: "SE",  instituicao: "AMASE"  )
grupoSelecionado.inscritos.create( nome: "Edinaldo César Santos Junior",  estado: "SE",  instituicao: "AMASE"  )
grupoSelecionado.inscritos.create( nome: "Maria de Fátima Ferreira de Barros",  estado: "SE",  instituicao: "AMASE"  )
grupoSelecionado.inscritos.create( nome: "Juliana Nogueira Galvão Martins",  estado: "SE",  instituicao: "AMASE"  )
grupoSelecionado.inscritos.create( nome: "ELAYNE DA SILVA RAMOS CANTUARIA",  estado: "AP",  instituicao: "AMAAP" )
grupoSelecionado.inscritos.create( nome: "Elio Braz Mendes",  estado: "PE",  instituicao: "AMEPE" )
grupoSelecionado.inscritos.create( nome: "EMILIANO CÉSAR COSTA GALVÃO DE FRANÇA",  estado: "PE",  instituicao: "AMEPE"  )
grupoSelecionado.inscritos.create( nome: "FABIO FRANCISCO ESTEVES",  estado: "DF",  instituicao: "AMAGIS-DF" )
grupoSelecionado.inscritos.create( nome: "IRINEU DE OLIVEIRA FILHO",  estado: "DF",  instituicao: "AMAGIS DF"  )
grupoSelecionado.inscritos.create( nome: "PAULA AFONCINA BARROS RAMALHO",  estado: "DF",  instituicao: "AMAGIS/DF"  )
grupoSelecionado.inscritos.create( nome: "Glaucia Falsarella Pereira Foley",  estado: "DF",  instituicao: "AMAGIS/DF"  )
grupoSelecionado.inscritos.create( nome: "Rafael Rodrigues de Castro Silva",  estado: "DF",  instituicao: "AMAGIS/DF"  )
grupoSelecionado.inscritos.create( nome: "John Silas da Silva",  estado: "AL",  instituicao: "ALMAGIS" )
grupoSelecionado.inscritos.create( nome: "Kerley Regina Ferreira de Arruda Alcântara",  estado: "RO",  instituicao: "AMERON" )
grupoSelecionado.inscritos.create( nome: "Lorival Ferreira dos Santos",  estado: "SP",  instituicao: "AMATRA XV" )
grupoSelecionado.inscritos.create( nome: "BRUNA DOS SANTOS COSTA RODRIGUES",  estado: "CE",instituicao: "", cidade: "Graça")
grupoSelecionado.inscritos.create( nome: "RICARDO ALEXANDRE DA SILVA COSTA",  estado: "CE",  instituicao: "ACM"  )
grupoSelecionado.inscritos.create( nome: "Sabino da Silva Marques",  estado: "AM",  instituicao: "AMAZON" )
grupoSelecionado.inscritos.create( nome: "HUGO DE SOUZA SILVA",  estado: "GO",  instituicao: "ASMEGO" )
grupoSelecionado.inscritos.create( nome: "EVERTON VILLARON DE SOUZA",  estado: "MG",  instituicao: "AMAGIS" )
grupoSelecionado.inscritos.create( nome: "Jorge Luiz Ramos",  estado: "ES",  instituicao: "AMAGES" )
grupoSelecionado.inscritos.create( nome: "VERA LÚCIA DEBONI",  cidade: "PORTO ALEGRE", estado: "RS",  instituicao: "AJURIS" )
grupoSelecionado.inscritos.create( nome: "ANTONIO CARLOS RIBEIRO",  cidade: "PORTO ALEGRE", estado: "RS",  instituicao: "AJURIS"  )
grupoSelecionado.inscritos.create( nome: "KAREN LUISE VILANOVA BATISTA DE SOUZA PINHEIRO",  cidade: "PORTO ALEGRE", estado: "RS", instituicao: "AJURIS"  )
grupoSelecionado.inscritos.create( nome: "Sansão Ferreira Barreto",  estado: "SP",  instituicao: "APAMAGIS" )
grupoSelecionado.inscritos.create( nome: "Marcel ferreira dos santos",  cidade: "Maringá", estado: "PR",  instituicao: "AMAPAR" )
grupoSelecionado.inscritos.create( nome: "Guilherme Cerqueira",  cidade: "Rio de Janeiro", estado: "RJ",  instituicao: "TRT 1ª REGIÃO"  )
grupoSelecionado.inscritos.create( nome: "ADMILSON ALVES BESERRA",  estado: "RJ",  instituicao: "Educação" )
grupoSelecionado.inscritos.create( nome: "Agda Yokowo dos Santos Rocha",  estado: "DF",  instituicao: "Assistente Social"  )
grupoSelecionado.inscritos.create( nome: "Álisson Rafael de sousa lopes",  estado: "DF",  instituicao: "Professor e Advogado"  )
grupoSelecionado.inscritos.create( nome: "ANA CESARINA FELIX DOS SANTOS LIMA",  estado: "DF",  instituicao: "ADVOGADA/CIVEL E FAMÍLIA"  )
grupoSelecionado.inscritos.create( nome: "Andreia de Oliveira",  estado: "SP",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Andreza de Paiva de Oliveira",  estado: "SP",  instituicao: "EDUCAFRO"  )
grupoSelecionado.inscritos.create( nome: "Ângela Maria da Silva",  estado: "Df",  instituicao: "estudante de direito"  )
grupoSelecionado.inscritos.create( nome: "Artur Antônio dos Santos Araujo",  estado: "DF",  instituicao: "Bancário"  )
grupoSelecionado.inscritos.create( nome: "camila cardozo melchior",  estado: "df"  )
grupoSelecionado.inscritos.create( nome: "CARLA CRISTINA LINS PITOMBO",  estado: "DF",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "CAROLINA DA SILVA PEREIRA",  cidade: "Rio de Janeiro", estado: "RJ"  )
grupoSelecionado.inscritos.create( nome: "CEZINON PEREIRA DOS SANTOS",  estado: "DF",  instituicao: "SANEAMENTO"  )
grupoSelecionado.inscritos.create( nome: "Cintia",  estado: "SP",  instituicao: "Estudante"  )
grupoSelecionado.inscritos.create( nome: "Cláudia Sardinha de Magalhães",  estado: "Df",  instituicao: "Estudante"  )
grupoSelecionado.inscritos.create( nome: "CLEIDE TAVARES ABADIA",  estado: "MG",  instituicao: "ADVOGADA e ESTUDANTE"  )
grupoSelecionado.inscritos.create( nome: "Conceição Aparecida Rezende dos Santos",  estado: "DF",  instituicao: "Assistente Social"  )
grupoSelecionado.inscritos.create( nome: "Daniel Lucas Silva Santiago",  estado: "DF",  instituicao: "Direito"  )
grupoSelecionado.inscritos.create( nome: "Daniela Lourenço",  estado: "Df",  instituicao: "desempregada"  )
grupoSelecionado.inscritos.create( nome: "Daniele Conceição dos Santos",  estado: "RJ"  )
grupoSelecionado.inscritos.create( nome: "Dayane Martins Araújo",  estado: "DF",  instituicao: "Agente Comunitário de Justiça e Cidadania"  )
grupoSelecionado.inscritos.create( nome: "Deise Benedito",  estado: "DF",  instituicao: "Perita MNPCT"  )
grupoSelecionado.inscritos.create( nome: "Deivson dos Santos",  estado: "DF",  instituicao: "Tecnico Judiciário"  )
grupoSelecionado.inscritos.create( nome: "Denise da Costa Eleutério",  estado: "DF",  instituicao: "Advogada/Professora"  )
grupoSelecionado.inscritos.create( nome: "EDILSON ALVES CRISTALINO PEREIRA",  estado: "DF",  instituicao: "CONSULTOR ORGANIZACIONAL"  )
grupoSelecionado.inscritos.create( nome: "Elayne Cristina dos Santos Almeida",  estado: "SE",  instituicao: "Graduanda em Direito"  )
grupoSelecionado.inscritos.create( nome: "Elias Roberto Leão da Silva",  estado: "DF",  instituicao: "Advogado"  )
grupoSelecionado.inscritos.create( nome: "Ernesto Nunes",  estado: "Df",  instituicao: "estudante"  )
grupoSelecionado.inscritos.create( nome: "Ester Silva Dourado",  estado: "Df",  instituicao: "Lojista"  )
grupoSelecionado.inscritos.create( nome: "Fernanda Sacramento Samora",  estado: "ES",  instituicao: "Estudante de Direito"  )
grupoSelecionado.inscritos.create( nome: "fernando marinho",  estado: "SP",  instituicao: "Assistente Jurídico do MP/SP"  )
grupoSelecionado.inscritos.create( nome: "Firmiane Venâncio do Carmo Souza",  estado: "BA",  instituicao: "Defensora Pública"  )
grupoSelecionado.inscritos.create( nome: "FRANCINEIDE MARINHO SANTOS",  estado: "DF",  instituicao: "ESTUDANTE"  )
grupoSelecionado.inscritos.create( nome: "Gabriel Alex Pinto de Oliveira",  estado: "SP",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Ilana Dandara Campos Alves",  cidade: "Rio de Janeiro", estado: "RJ",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "IVONE RIBEIRO DE OLIVEIRA",  estado: "SP",  instituicao: "ADVOGADA/ CIVIL"  )
grupoSelecionado.inscritos.create( nome: "Ivonete Pereira Rodrigues",  estado: "DF",  instituicao: "Agente Comunitário de Justiça e Cidadania"  )
grupoSelecionado.inscritos.create( nome: "Jacira Ribeiro Campos",  estado: "DF", instituicao: "Estudante"  )
grupoSelecionado.inscritos.create( nome: "Jamile Barbosa Correia",  cidade: "Rio de Janeiro", estado: "RJ",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Janaina Coelho azevedo",  estado: "DF",  instituicao: "Atriz"  )
grupoSelecionado.inscritos.create( nome: "JESUS JAIRO ALMEIDA DE LACERDA",  estado: "SE",  instituicao: "DEFENSORIA PÚBLICA DO ESTADO DE SERGIPE"  )
grupoSelecionado.inscritos.create( nome: "JOAO PAULO DA SILVA LEANDRO FERREIRA LIMA",  estado: "DF",  instituicao: "ADVOGADO"  )
grupoSelecionado.inscritos.create( nome: "José Hélio Queiroz",  estado: "PR",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "JOSÉ LEÓ DE CARVALHO NETO",  estado: "SE",  instituicao: "DEFENSORIA PÚBLICA DO ESTADO DE SERGIPE"  )
grupoSelecionado.inscritos.create( nome: "Joseanes Lima dos Santos",  estado: "DF", instituicao: "Relaçoes Internacionais"  )
grupoSelecionado.inscritos.create( nome: "JOSEFINA SERRA DOS SANTOS",  estado: "DF",  instituicao: "Advogada- Cível, Criminal, Previdência, Trabalhista."  )
grupoSelecionado.inscritos.create( nome: "Joyce Tatiane Andrade",  estado: "SP", instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "Julia Angel Santos de Souza",  cidade: "Rio de Janeiro", estado: "RJ",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Juliana Helena Da Cruz",  estado: "DF",  instituicao: "ASSISTENTE SOCIAL"  )
grupoSelecionado.inscritos.create( nome: "Júnia Pessôa Martins",  estado: "DF",  instituicao: "ASSISTENTE SOCIAL tjdft"  )
grupoSelecionado.inscritos.create( nome: "Keitchele Lima da Silva",  estado: "SP",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Liciane da Costa Botelho",  estado: "DF",  instituicao: "Agente comunitária"  )
grupoSelecionado.inscritos.create( nome: "Lilian da silva bomfim",  estado: "SP",  instituicao: "Corretora"  )
grupoSelecionado.inscritos.create( nome: "LORENA",  estado: "RJ",  instituicao: "Educadro8"  )
grupoSelecionado.inscritos.create( nome: "Luana Melo da Silva",  estado: "DF",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "luciene gomes martins",  estado: "df",  instituicao: "estudante de Direito"  )
grupoSelecionado.inscritos.create( nome: "Ludmila Weizmann Suaid Levyski",  estado: "DF",  instituicao: "Assistente Social"  )
grupoSelecionado.inscritos.create( nome: "Luis Fausto Dias de Valois Santos",  estado: "SE"  )
grupoSelecionado.inscritos.create( nome: "Luis Felgueira José",  estado: "DF",  instituicao: "Estudante de Jornalismo"  )
grupoSelecionado.inscritos.create( nome: "Luiz Henrique de Freitas Silva",  estado: "SP",  instituicao: "EDUCAFRO"  )
grupoSelecionado.inscritos.create( nome: "Luiz Víctor do Espírito Santo Silva",  estado: "DF",  instituicao: "Servidor do Conselho Nacional de Justiça"  )
grupoSelecionado.inscritos.create( nome: "MAGALY D. A. MORAIS", estado: "SP", instituicao: "TRADUTORA"  )
grupoSelecionado.inscritos.create( nome: "MARCELO RAIMUNDO DE SOUZA FILHO",  estado: "PI",  instituicao: "Estudante/Servidor Publico - Pesquiso Ações Afirmativas e Questões Étnico Raciais no Judiciário.")
grupoSelecionado.inscritos.create( nome: "MÁRCIA REGINA DOS SANTOS VIRGENS",  estado: "BA",  instituicao: "Procuradora de Justiça/Cível"  )
grupoSelecionado.inscritos.create( nome: "Marcio Romualdo Santos da Silva",  estado: "SP",  instituicao: "Advgogado"  )
grupoSelecionado.inscritos.create( nome: "Marcus Vinícius do Nascimento Silva",  estado: "DF",  instituicao: "Advogado"  )
grupoSelecionado.inscritos.create( nome: "Maria dos Navegantes Queiroz",  estado: "PR",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "MARIA HELENA DA SILVA",  estado: "DF",  instituicao: "PROGRAMA JUSTIÇA COMUNITÁRIA - TJDFT"  )
grupoSelecionado.inscritos.create( nome: "MARIA HELENA MORAIS BARBOSA",  estado: "DF",  instituicao: "PROGRAMA JUSTIÇA COMUNITÁRIA - TJDFT"  )
grupoSelecionado.inscritos.create( nome: "MARIA INES ESCOBAR DA COSTA",  estado: "CE",  instituicao: "PROFESSORA UNIVERSITÁRIA - UFCA, DOUTORANDA USP"  )
grupoSelecionado.inscritos.create( nome: "Maria Lucia da Silva",  estado: "DF",  instituicao: "ABBP"  )
grupoSelecionado.inscritos.create( nome: "MARIA LUCIA DE LIMA",  estado: "DF",  instituicao: "Programa Justiça Comunitária do TJDFT"  )
grupoSelecionado.inscritos.create( nome: "Maria Paula Costa de Carvalho",  estado: "DF",  instituicao: "Estudante"  )
grupoSelecionado.inscritos.create( nome: "MARIA SUELY RIBEIRO",  estado: "DF",  instituicao: "MEDIAÇÃO COMUNITARIA"  )
grupoSelecionado.inscritos.create( nome: "Marina Pereira de Andrade",  estado: "DF",  instituicao: "Aposentada"  )
grupoSelecionado.inscritos.create( nome: "Maty Lice Brancher Gueye",  estado: "DF",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "Mayara Silva de Souza",  estado: "SP",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "Michelle Vieira Cardoso",  estado: "Df",  instituicao: "Estudante de Direito"  )
grupoSelecionado.inscritos.create( nome: "Milena Silva Dourado",  estado: "DF",  instituicao: "Lojista"  )
grupoSelecionado.inscritos.create( nome: "Narah Faustino da Penha",  cidade: "Rio de Janeiro", estado: "RJ",  instituicao: "Técnica de Enfermagem"  )
grupoSelecionado.inscritos.create( nome: "Nelzimar Maria Batista",  estado: "DF",  instituicao: "Psicóloga"  )
grupoSelecionado.inscritos.create( nome: "Nívea Fernanda Brasil dos Santos",  estado: "DF",  instituicao: "UniCEUB"  )
grupoSelecionado.inscritos.create( nome: "Paula Gonçalves Ribeiro",  estado: "DF"  )
grupoSelecionado.inscritos.create( nome: "Raquel Dannity Dias Santos",  estado: "DF",  instituicao: "Estagiária de serviço social"  )
grupoSelecionado.inscritos.create( nome: "Regina Apolinário Ferreira",  estado: "RJ",  instituicao: "Direto"  )
grupoSelecionado.inscritos.create( nome: "Rejane Bispo da Silva",  estado: "DF",  instituicao: "Agente Comunitário de Justiça e Cidadania"  )
grupoSelecionado.inscritos.create( nome: "Roosevelt Rodrigues",  estado: "DF",  instituicao: "advocacia"  )
grupoSelecionado.inscritos.create( nome: "ROSELI DA SILVA SANTOS",  estado: "SP",  instituicao: "advogada"  )
grupoSelecionado.inscritos.create( nome: "Silvia Virgínia Silva de Souza",  estado: "SP",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "Sita Saldanha",  estado: "SP",  instituicao: "EStudante"  )
grupoSelecionado.inscritos.create( nome: "solange",  estado: "DF",  instituicao: "PROFESSORA - EDUCAÇÃO PROFISSIONAL"  )
grupoSelecionado.inscritos.create( nome: "Soraya Mendes de Souza da Silva",  estado: "DF",  instituicao: "Estagiária"  )
grupoSelecionado.inscritos.create( nome: "Suelen Queiroz",  estado: "PR",  instituicao: "Eduafro"  )
grupoSelecionado.inscritos.create( nome: "SUELENITO DOS SANTOS",  estado: "DF",  instituicao: "Agente Comunitário"  )
grupoSelecionado.inscritos.create( nome: "Tamara Gonçalves Ferreira Santos",  estado: "Df",  instituicao: "Psicóloga clínica"  )
grupoSelecionado.inscritos.create( nome: "THAIS CRUZ ANDREOZZI",  estado: "DF",  instituicao: "PSICOLOGA"  )
grupoSelecionado.inscritos.create( nome: "Thalita Ariane Brasil Botelho",  estado: "DF", instituicao: "Cursando Direito"  )
grupoSelecionado.inscritos.create( nome: "THAYNNE AGUIAR GOMES DE ANDRADE AMMON",  estado: "RJ",  instituicao: "Profissão / Área de atuação"  )
grupoSelecionado.inscritos.create( nome: "Thays do Carmo da Silva",  estado: "DF",  instituicao: "advogada"  )
grupoSelecionado.inscritos.create( nome: "VALDECI PEREIRA DA SILVA",  estado: "DF",  instituicao: "MEDIAÇÃO COMUNITÁRIA"  )
grupoSelecionado.inscritos.create( nome: "VALDENE ALVES LEITE DA ROCHA",  estado: "DF",  instituicao: "MEDIAÇÃO COMUNITÁRIA"  )
grupoSelecionado.inscritos.create( nome: "Vera Lúcia Santana Araújo",  estado: "DF",  instituicao: "Advogada"  )
grupoSelecionado.inscritos.create( nome: "Vera Lucia Soares",  estado: "DF",  instituicao: "TJDFT"  )
grupoSelecionado.inscritos.create( nome: "Verônica Gomes de Lima",  estado: "Rj",  instituicao: "Educafro"  )
grupoSelecionado.inscritos.create( nome: "Virgínia Tomazelli Ramos",  estado: "ES",  instituicao: "Estudante de Direito"  )
grupoSelecionado.inscritos.create( nome: "WAGNER ALVES DE MORAIS",  estado: "SP",  instituicao: "ADVOGADO"  )
grupoSelecionado.inscritos.create( nome: "WALESKA MIGUEL BATISTA",  estado: "SP",  instituicao: "ADVOGADA"  )
